#!/usr/bin/env python3
"""Package the add-on into a .ankiaddon zip.

Anki expects the add-on's files at the *top level* of the archive, not nested in
a folder, so we zip the contents of src/photo2cards rather than the directory.

    python build.py            -> dist/photo2cards.ankiaddon

Double-click the result (or Anki → Tools → Add-ons → Install from file) to
sideload it. For AnkiWeb, upload the same file.
"""

from __future__ import annotations

import json
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ADDON_DIR = ROOT / "src" / "photo2cards"
DIST = ROOT / "dist"

#: meta.json holds the *user's* saved config, including their API key. It is
#: generated by Anki at runtime and must never end up in a distributed zip.
EXCLUDE_NAMES = {"meta.json", ".DS_Store", "Thumbs.db"}
EXCLUDE_DIRS = {"__pycache__", ".pytest_cache", ".ruff_cache"}


def iter_files():
    for path in sorted(ADDON_DIR.rglob("*")):
        if not path.is_file():
            continue
        if any(part in EXCLUDE_DIRS for part in path.parts):
            continue
        if path.name in EXCLUDE_NAMES or path.suffix == ".pyc":
            continue
        yield path


def main() -> int:
    if not ADDON_DIR.is_dir():
        print(f"error: {ADDON_DIR} not found", file=sys.stderr)
        return 1

    manifest = json.loads((ADDON_DIR / "manifest.json").read_text(encoding="utf-8"))
    package = manifest["package"]
    version = manifest.get("human_version", "0.0.0")

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True, exist_ok=True)

    out = DIST / f"{package}.ankiaddon"
    count = 0
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in iter_files():
            zf.write(path, path.relative_to(ADDON_DIR).as_posix())
            count += 1

    size_kb = out.stat().st_size / 1024
    print(f"{out.relative_to(ROOT)}  ({count} files, {size_kb:.0f} KB, v{version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
